import type { Metadata } from "next";
import { Navigation } from "../features/navigation/index";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Cart } from "@/features/cart";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	viewport: "width=device-width, initial-scale=1.0"
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Navigation />
				<Cart />
				{children}
			</body>
		</html>
	);
}
